### ISSUE TITLE
URL linkable patterns request

### ISSUE THREAD

**Issue by bblodfon** [helbling/passist#12]
Hi Christian!

I hope you're doing good during these interesting corona times!

Have you maybe implemented a way to link a pattern via a (REST) URL? For example, hitting the link https://passist.org/?Siteswap=77862&persons=2#siteswap_col or something close to it and get to the pattern information instantly? I want to link some of these patterns that I have written in some other documentation I am keeping: https://bblodfon.github.io/my-siteswaps/2person_passing.html.

**Comment by helbling** [comment]
Hi John

I'm good. We even had a small spontaneous juggling meetup yesterday instead of the swiss national convention that can't be held this year. Hope you're well as well!

I'm currently working on a big update featuring 3d animations and modular js code using svelte/sapper in the sapper branch. Testable on https://beta.passist.org. 
I've already implemented linkable urls there. For example: https://beta.passist.org/siteswap/77862?nJugglers=2

Note that I might change the url-scheme and that the beta could sometimes be in some unusable state.
But I think i'm ready to release that soon (tm).

**Comment by bblodfon** [comment]
Looks amazing, nice work there! Thanks for the link, I will use that and change it when it's released. If I see anything not working, I will let you know :)
